```{r, message=FALSE, warning=FALSE}
library(vtree)
library(dplyr)
```

# Source

https://data.ottawapolice.ca/datasets/76a54b7f7ef44ab1b78dd96f3061c7cb_0

# License

https://data.ottawapolice.ca/pages/open-data-licence


```{r}
data <- read.csv("traffic_stops.csv")

traffic_stops <- data |>
  rename(race = Driver.Race, age = Driver.Age, gender = Driver.Gender, 
    city = Driver.City, province = Driver.Province,
    how_cleared = How.Cleared, date = Occurred.Date, year = Occurred.Year,
    hour = Occurred.Hour, day = Day.of.Week) |>
  select(-Occurrence.Number, -x_coordinate, -y_coordinate, -x, -y, -OBJECTID, -Location, -Neighbourhood, -date) |>
  filter(!is.na(race) & age != "" & gender != "") |>
  filter(gender != "D", age != "-15")
```

Each row of the data represents a traffic stop. 

"Final" category means that police stoped the car and let it go. 

```{r}
vtree(traffic_stops, "how_cleared", horiz = F)
```

```{r}
vtree(traffic_stops, "race how_cleared", horiz = T)

```

Shiny version is accessed with svtree()

```{r}
svtree(traffic_stops, "race how_cleared", horiz = F)

```

parameter race=White is dychotomizing race in White/non-White 


```{r}
svtree(traffic_stops, "race=White how_cleared", horiz = F)

```
```{r}
svtree(traffic_stops, "age race=White how_cleared=Final", horiz = T)

```


```{r}
vtree(traffic_stops, "race=White age", 
      summary = "how_cleared=Final %leafonly%", 
      splitwidth = Inf)
```







